- hosts: localhost
  become: no
  vars:
    env: non-prod
    app_name: test
    template_name: abc_template
    vm_folder:
    size: medium
    os_type: linux
    network_name: abc
    ip_address: 192.168.1.51
    netmask: 255.255.255.0
    gateway: 192.168.1.254
    domain_name: example.com
    dns_servers:
      - 8.8.8.8
    server_role: webserver
  vars_files:
    - "config/infra/{{ env }}/main.yml"
    - "config/infra/{{ env }}/{{ os_type[0:1] + '1-' + size }}.yml"
  roles:
    - vmware-deploy