---
- disk:
  - size_gb: 100
    type: thin
    autoselect_datastore: yes
  domain: "{{ domain_name }}"
  dns_servers:
  - 8.8.4.4
  memory: 4096
  cpu: 2
  template: windows
- disk:
  - size_gb: 100
    type: thin
    autoselect_datastore: yes
  domain: "{{ domain_name }}"
  dns_servers:
  - 8.8.4.4
  memory: 4096
  cpu: 2
  template: rhel73
- disk:
  - size_gb: 100
    type: thin
    autoselect_datastore: yes
  domain: "{{ domain_name }}"
  dns_servers:
  - 8.8.4.4
  memory: 4096
  cpu: 2
  template: "{{ template_name }}"
- disk:
  - size_gb: 100
    type: thin
    autoselect_datastore: yes
  domain: "{{ domain_name }}"
  dns_servers:
  - 8.8.4.4
  memory: 4096
  cpu: 2
  template: "{{ template_name }}"